### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by mariussoutier** [jamesward/play-framework-chrome-tools#4]
When reloading an Anguar app in the browser, I get the following error a few reloads:

```
    Error in event handler for 'undefined': Cannot call method 'removeEventListener' of null TypeError: Cannot call method 'removeEventListener' of null
        at bindShortcuts (chrome-extension://alelhddbbhepgpmgidjdcjakblofbmce/javascripts/content_script.js:548:7)
        at chrome-extension://alelhddbbhepgpmgidjdcjakblofbmce/javascripts/content_script.js:78:4
        at Event.dispatchToListener (event_bindings:356:21)
        at Event.dispatch_ (event_bindings:342:27)
        at Event.dispatch (event_bindings:362:17)
        at chromeHidden.Port.dispatchOnConnect.isExternal (miscellaneous_bindings:165:24)
        at Event.dispatchToListener (event_bindings:356:21)
        at Event.dispatch_ (event_bindings:342:27)
        at Event.dispatch (event_bindings:362:17)
        at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:253:22) event_bindings:346
    Error in event handler for 'undefined': Cannot read property 'textContent' of null TypeError: Cannot read property 'textContent' of null
        at chrome-extension://dchhggpgbommpcjpogaploblnpldbmen/play-framework-chrome-tools.js:18:32
        at chromeHidden.Port.sendMessageImpl (miscellaneous_bindings:287:9)
        at Event.dispatchToListener (event_bindings:356:21)
        at Event.dispatch_ (event_bindings:342:27)
        at Event.dispatch (event_bindings:362:17)
        at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:253:22)
        at chrome-extension://fngmhnnpilhplaeedifhccceomclgfbg/alternet/jquery-1.7.2.min.js:3:25601
        at L (chrome-extension://fngmhnnpilhplaeedifhccceomclgfbg/alternet/jquery-1.7.2.min.js:3:25924)
        at chrome-extension://fngmhnnpilhplaeedifhccceomclgfbg/alternet/jquery-1.7.2.min.js:3:27070
        at chrome-extension://fngmhnnpilhplaeedifhccceomclgfbg/alternet/jquery-1.7.2.min.js:4:29596 
```

**Comment by mariussoutier** [comment]
I guess you can ignore this one, it only fires when you have "pause on exceptions" enabled. Otherwise it works fine.
